# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  default_transaction_mode: IMMEDIATE
  encoding: utf-8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  reader:
    <<: *default
    database: storage/development.sqlite3
    database_tasks: false
    readonly: true
  writer:
    <<: *default
    database: storage/development.sqlite3
    pool: 1
    schema_dump: schema.rb
  cable:
    <<: *default
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate
    schema_dump: cable_schema.rb
  cache:
    <<: *default
    database: storage/development_cache.sqlite3
    migrations_paths: db/cache_migrate
    schema_dump: cache_schema.rb
  queue:
    <<: *default
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate
    schema_dump: queue_schema.rb
  session:
    <<: *default
    database: storage/development_session.sqlite3
    migrations_paths: db/session_migrate
    schema_dump: session_schema.rb
  storage:
    <<: *default
    database: storage/development_storage.sqlite3
    migrations_paths: db/storage_migrate
    schema_dump: storage_schema.rb

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  reader:
    <<: *default
    database: storage/test.sqlite3
    database_tasks: false
    readonly: true
  writer:
    <<: *default
    database: storage/test.sqlite3
    pool: 1
    schema_dump: schema.rb
  cable:
    <<: *default
    database: storage/test_cable.sqlite3
    migrations_paths: db/cable_migrate
    schema_dump: cable_schema.rb
  cache:
    <<: *default
    database: storage/test_cache.sqlite3
    migrations_paths: db/cache_migrate
    schema_dump: cache_schema.rb
  queue:
    <<: *default
    database: storage/test_queue.sqlite3
    migrations_paths: db/queue_migrate
    schema_dump: queue_schema.rb
  session:
    <<: *default
    database: storage/test_session.sqlite3
    migrations_paths: db/session_migrate
    schema_dump: session_schema.rb
  storage:
    <<: *default
    database: storage/test_storage.sqlite3
    migrations_paths: db/storage_migrate
    schema_dump: storage_schema.rb

# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  reader:
    <<: *default
    database: storage/production.sqlite3
    database_tasks: false
    readonly: true
  writer:
    <<: *default
    database: storage/production.sqlite3
    pool: 1
    schema_dump: schema.rb
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
    schema_dump: cable_schema.rb
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
    schema_dump: cache_schema.rb
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
    schema_dump: queue_schema.rb
  session:
    <<: *default
    database: storage/production_session.sqlite3
    migrations_paths: db/session_migrate
    schema_dump: session_schema.rb
  storage:
    <<: *default
    database: storage/production_storage.sqlite3
    migrations_paths: db/storage_migrate
    schema_dump: storage_schema.rb
